// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_7SilSmt3708tsJ1yoDKTvOUdLi2sdI',
    appId: '1:1027615173078:android:eb8e4404da538c1b8b5c77',
    messagingSenderId: '1027615173078',
    projectId: 'expense-tracker-8b7eb',
    storageBucket: 'expense-tracker-8b7eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6N5emWA0H3c9QXY13sxoKnuCJ7Fnnftk',
    appId: '1:1027615173078:ios:2e4a254298a9780c8b5c77',
    messagingSenderId: '1027615173078',
    projectId: 'expense-tracker-8b7eb',
    storageBucket: 'expense-tracker-8b7eb.firebasestorage.app',
    iosClientId: '1027615173078-ju7nojcmeej13nnb3jmsntatvt8o53d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
